
import SwiftUI

struct QRCodeView: View {
    let qrCodeImage: UIImage // This will be generated by QRCodeService

    var body: some View {
        VStack {
            Image(uiImage: qrCodeImage)
                .resizable()
                .interpolation(.none)
                .scaledToFit()
                .padding()
                .modifier(liquidGlass(.floating))
            
            ShareLink(item: Image(uiImage: qrCodeImage), preview: SharePreview("QR Code", image: Image(uiImage: qrCodeImage))) {
                Label("Teilen", systemImage: "square.and.arrow.up")
            }
            .modifier(interactiveGlass())
        }
        .navigationTitle("QR Code")
    }
}

#if DEBUG
struct QRCodeView_Previews: PreviewProvider {
    static var previews: some View {
        // Create a dummy QR code for preview
        let qrCodeService = QRCodeService.shared
        let dummyImage = qrCodeService.generateQRCode(from: "preview-dummy-data") ?? UIImage()
        
        return QRCodeView(qrCodeImage: dummyImage)
    }
}
#endif
